'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Common
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProLab.Data.Common", GetType(Common).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CityName FROM City WHERE CityName=@CityName AND Id!=@Id.
        '''</summary>
        Friend Shared ReadOnly Property CheckCityName() As String
            Get
                Return ResourceManager.GetString("CheckCityName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT CountryName FROM Country WHERE CountryName=@CountryName AND Id!=@Id.
        '''</summary>
        Friend Shared ReadOnly Property CheckCountryName() As String
            Get
                Return ResourceManager.GetString("CheckCountryName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT StateName FROM State WHERE StateName=@StateName AND Id!=@Id.
        '''</summary>
        Friend Shared ReadOnly Property CheckStateName() As String
            Get
                Return ResourceManager.GetString("CheckStateName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM City WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property DeleteCity() As String
            Get
                Return ResourceManager.GetString("DeleteCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM Country WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property DeleteCountry() As String
            Get
                Return ResourceManager.GetString("DeleteCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM State WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property DeleteState() As String
            Get
                Return ResourceManager.GetString("DeleteState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Id,CityName FROM City.
        '''</summary>
        Friend Shared ReadOnly Property GetAllCity() As String
            Get
                Return ResourceManager.GetString("GetAllCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM  Country ORDER BY CountryName.
        '''</summary>
        Friend Shared ReadOnly Property GETALLCOUNTRY() As String
            Get
                Return ResourceManager.GetString("GETALLCOUNTRY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM  ReportStatus.
        '''</summary>
        Friend Shared ReadOnly Property GetAllReportStatus() As String
            Get
                Return ResourceManager.GetString("GetAllReportStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM City WHERE Id=@Id .
        '''</summary>
        Friend Shared ReadOnly Property GetCityById() As String
            Get
                Return ResourceManager.GetString("GetCityById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM City WHERE CityName=@CityName.
        '''</summary>
        Friend Shared ReadOnly Property GetCityByName() As String
            Get
                Return ResourceManager.GetString("GetCityByName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM City WHERE CountryId=@CountryId AND StateId=@StateId  ORDER BY CityName.
        '''</summary>
        Friend Shared ReadOnly Property GetCityByStateId() As String
            Get
                Return ResourceManager.GetString("GetCityByStateId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM  Country WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetCountryById() As String
            Get
                Return ResourceManager.GetString("GetCountryById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Country WHERE CountryName=@CountryName.
        '''</summary>
        Friend Shared ReadOnly Property GetCountryByName() As String
            Get
                Return ResourceManager.GetString("GetCountryByName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select a.Id from City a,Settings b where a.CityName=b.Value.
        '''</summary>
        Friend Shared ReadOnly Property GetDefaultCity() As String
            Get
                Return ResourceManager.GetString("GetDefaultCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select a.Id from Country a,Settings b where a.CountryName=b.Value.
        '''</summary>
        Friend Shared ReadOnly Property GetDefaultCountry() As String
            Get
                Return ResourceManager.GetString("GetDefaultCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select a.Id from State a,Settings b where a.StateName=b.Value.
        '''</summary>
        Friend Shared ReadOnly Property GetDefaultState() As String
            Get
                Return ResourceManager.GetString("GetDefaultState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM State WHERE CountryId=@CountryId ORDER BY StateName.
        '''</summary>
        Friend Shared ReadOnly Property GetStateByCountryId() As String
            Get
                Return ResourceManager.GetString("GetStateByCountryId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM State WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetStateById() As String
            Get
                Return ResourceManager.GetString("GetStateById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM State WHERE StateName=@StateName.
        '''</summary>
        Friend Shared ReadOnly Property GetStateByName() As String
            Get
                Return ResourceManager.GetString("GetStateByName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Users WHERE UserName = @UserName.
        '''</summary>
        Friend Shared ReadOnly Property GetUserByName() As String
            Get
                Return ResourceManager.GetString("GetUserByName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO City(CountryId,StateId,CityName,IsActive,CreateDate,CreateBy) VALUES(@CountryId,@StateId,@CityName,@IsActive,@CreateDate,@CreateBy).
        '''</summary>
        Friend Shared ReadOnly Property SaveCity() As String
            Get
                Return ResourceManager.GetString("SaveCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO Country(CountryName,IsActive,CreateDate,CreateBy) VALUES(@CountryName,@IsActive,@CreateDate,@CreateBy) .
        '''</summary>
        Friend Shared ReadOnly Property SaveCountry() As String
            Get
                Return ResourceManager.GetString("SaveCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO State(CountryId,StateName,IsActive,CreateDate,CreateBy) VALUES(@CountryId,@StateName,@IsActive,@CreateDate,@CreateBy) .
        '''</summary>
        Friend Shared ReadOnly Property SaveState() As String
            Get
                Return ResourceManager.GetString("SaveState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE City SET CountryId=@CountryId,StateId=@StateId,CityName=@CityName,IsActive=@IsActive, UpdateDate=@UpdateDate, UpdateBy=@UpdateBy WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property UpdateCity() As String
            Get
                Return ResourceManager.GetString("UpdateCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Country SET CountryName=@CountryName,IsActive=@IsActive , UpdateDate=@UpdateDate, UpdateBy=@UpdateBy Where Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property UpdateCountry() As String
            Get
                Return ResourceManager.GetString("UpdateCountry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE State SET CountryId=@CountryId,StateName=@StateName,IsActive=@IsActive , UpdateDate=@UpdateDate, UpdateBy=@UpdateBy WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property UpdateState() As String
            Get
                Return ResourceManager.GetString("UpdateState", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
