'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class PatientBill
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProLab.Data.PatientBill", GetType(PatientBill).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select 1 From [dbo].[PatientBills] Where LTrim(RTrim(BillNo)) = @BillNo.
        '''</summary>
        Friend Shared ReadOnly Property FindBillNumber() As String
            Get
                Return ResourceManager.GetString("FindBillNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT a.Id,a.BillNo,a.PatientId,a.PaymentDateTime as InvoiceDate,a.PaymentMode,a.TotalAmount,a.Status FROM PatientBills a,Patients b where a.PatientId=b.Id AND b.FirstName=@FirstName ORDER BY a.CreateDate DESC.
        '''</summary>
        Friend Shared ReadOnly Property GetAllPatientBills() As String
            Get
                Return ResourceManager.GetString("GetAllPatientBills", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT c.Id,b.CreateDate as TransactionDate,d.Name as ServiceName,d.Amount,a.PatientTransactionId FROM PatientBillTransactions a JOIN PatientTransactions b on a.PatientTransactionId=b.Id JOIN ServiceTransactions c on a.ServiceTransactionId=c.Id JOIN Services d on c.ServiceID=d.Id WHERE a.PatientBillId=@BillId ORDER BY b.CreateDate DESC.
        '''</summary>
        Friend Shared ReadOnly Property GetPatientBillById() As String
            Get
                Return ResourceManager.GetString("GetPatientBillById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM PatientBills WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetPatientBillDetailsById() As String
            Get
                Return ResourceManager.GetString("GetPatientBillDetailsById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT B.Id,B.PatientBillId,A.DiscountAmount,A.TotalAmount,A.InvoiceDate,A.PaymentMode,C.FirstName,C.MiddleName,C.Lastname,C.Mobile,C.Gender,C.Age,D.DepositAmount
        '''		,E.FirstName as DoctorFname,E.LastName as DoctorLname
        '''FROM PatientBills A
        '''JOIN PatientBillTransactions B ON B.PatientBillId=A.Id
        '''JOIN Patients C ON C.Id = A.PatientId
        '''JOIN PatientTransactions D ON D.Id = B.PatientTransactionId
        '''LEFT JOIN Doctors E ON E.Id=D.RefDocId	
        '''WHERE A.Id=@BillId AND A.PatientId=@PatientId.
        '''</summary>
        Friend Shared ReadOnly Property GetPatientReceiptById() As String
            Get
                Return ResourceManager.GetString("GetPatientReceiptById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO BillChequeDetails(BillId,ChequeNo,ChequeDate,IFSCCode,BankName,CreateDate,CreateBy) VALUES(@BillId,@ChequeNo,@ChequeDate,@IFSCCode,@BankName,@CreateDate,@CreateBy).
        '''</summary>
        Friend Shared ReadOnly Property SaveBillChequeDetails() As String
            Get
                Return ResourceManager.GetString("SaveBillChequeDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to insert into PatientBills(BillNo,PatientId,TotalAmount,DiscountPercentage,DiscountAmount,Status,IsCancel,PaymentMode,PaymentDateTime,InvoiceDate,CreateDate,CreateBy,Remarks) values (@BillNo,@PatientId,@TotalAmount,@DiscountPercentage,@DiscountAmount,@Status,@IsCancel,@PaymentMode,@PaymentDateTime,@InvoiceDate,@CreateDate,@CreateBy,@Remarks); SELECT SCOPE_IDENTITY();.
        '''</summary>
        Friend Shared ReadOnly Property SavePatientBill() As String
            Get
                Return ResourceManager.GetString("SavePatientBill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO PatientBillTransactions(PatientBillId,PatientTransactionId,ServiceTransactionId,CreateDate,CreateBy) VALUES(@PatientBillId,@PatientTransactionId,@ServiceTransactionId,@CreateDate,@CreateBy).
        '''</summary>
        Friend Shared ReadOnly Property SavePatientBillTransctions() As String
            Get
                Return ResourceManager.GetString("SavePatientBillTransctions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update PatientBills set BillNo=@BillNo, TotalAmount=@TotalAmount,DiscountPercentage=@DiscountPercentage, DiscountAmount=@DiscountAmount, Status=@Status,IsCancel=@IsCancel,PaymentMode=@PaymentMode, Remarks=@Remarks, UpdateDate=@UpdateDate,UpdateBy=@UpdateBy where Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePatientBill() As String
            Get
                Return ResourceManager.GetString("UpdatePatientBill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE PatientTransactions SET BillGenerated=1 WHERE Id=@PatientTransactionId.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePatientBillStatus() As String
            Get
                Return ResourceManager.GetString("UpdatePatientBillStatus", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
