'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class PatientTransction
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProLab.Data.PatientTransction", GetType(PatientTransction).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM PatientTransactions WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property DeleteTransactionById() As String
            Get
                Return ResourceManager.GetString("DeleteTransactionById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM ServiceTransactions WHERE PatientTransactionId=@Id.
        '''</summary>
        Friend Shared ReadOnly Property DeleteTransactionServiceByTrasId() As String
            Get
                Return ResourceManager.GetString("DeleteTransactionServiceByTrasId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT SUM(c.Amount) AS TotalAmount, a.Id, a.PatientId, a.RefDocId, a.DepositAmount, a.SampleRequired, a.SampleReceived, a.SampleNumber, a.BillGenerated, a.CreateDate, a.Remarks
        '''FROM PatientTransactions a
        '''JOIN Patients b on a.PatientId=b.Id
        '''JOIN ServiceTransactions c on a.Id = c.PatientTransactionId
        '''GROUP BY a.Id, a.PatientId, a.RefDocId, a.DepositAmount, a.SampleRequired, a.SampleReceived, a.SampleNumber, a.BillGenerated, a.CreateDate, a.Remarks
        '''HAVING a.PatientId = @PatientId
        '''ORDER BY a.CreateDate D [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property GetAllPatientTransactions() As String
            Get
                Return ResourceManager.GetString("GetAllPatientTransactions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT SUM(c.Amount) AS TotalAmount, a.Id, a.PatientId, a.RefDocId, a.DepositAmount, a.SampleRequired, a.SampleReceived, a.SampleNumber, a.BillGenerated, a.CreateDate, a.Remarks
        '''FROM PatientTransactions a
        '''JOIN Patients b on a.PatientId=b.Id
        '''JOIN ServiceTransactions c on a.Id = c.PatientTransactionId
        '''GROUP BY a.Id, a.PatientId, a.RefDocId, a.DepositAmount, a.SampleRequired, a.SampleReceived, a.SampleNumber, a.BillGenerated, a.CreateDate, a.Remarks
        '''HAVING a.PatientId = @PatientId AND a.BillGenerated = 0        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property GetAllPatientUnpaidTransactions() As String
            Get
                Return ResourceManager.GetString("GetAllPatientUnpaidTransactions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select a.Id as ServiceTransactionId, b.Id as PatientTransactionId, cast(b.CreateDate as Date) as CreateDate, b.PatientId, 
        '''  d.CategoryName,c.Name as ServiceName, b.SampleNumber, e.FirstName + &apos; &apos; + e.Lastname as PatientName, f.Name as ReportStatus,
        '''  f.Id as ReportStatusId
        '''  from ServiceTransactions a
        '''  JOIN PatientTransactions b ON a.PatientTransactionId = b.Id
        '''  JOIN Services c ON a.ServiceID = c.Id
        '''  JOIN ServiceCategory d on c.CategoryId = d.Id
        '''  JOIN Patients e ON b.PatientId = e.Id
        '''  JOIN Rep [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property GetAllTransactionListByDate() As String
            Get
                Return ResourceManager.GetString("GetAllTransactionListByDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select value from Settings where Name=&apos;BillPrefix&apos;.
        '''</summary>
        Friend Shared ReadOnly Property GetBillNoForTransction() As String
            Get
                Return ResourceManager.GetString("GetBillNoForTransction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select DepositAmount from PatientTransactions where Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetDepositeAmountById() As String
            Get
                Return ResourceManager.GetString("GetDepositeAmountById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT c.Id as ServiceTransaction_Id, b.Id as ServiceTransaction_ServiceId,a.CategoryName as ServiceTransaction_SCategory,b.Name as ServiceTransaction_SName,b.Amount as ServiceTransaction_SAmount,C.PatientTransactionId AS Service_PatientTransactionId FROM ServiceCategory a,Services b,ServiceTransactions c where c.PatientTransactionId=@TransactionsId AND A.Id=B.CategoryId AND B.Id=C.ServiceID.
        '''</summary>
        Friend Shared ReadOnly Property GetPatientTransactionsById() As String
            Get
                Return ResourceManager.GetString("GetPatientTransactionsById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select  b.Id,b.CreateDate as TransactionDate,c.Name as ServiceName,b.Amount,b.PatientTransactionId from PatientTransactions a join ServiceTransactions b on a.Id=b.PatientTransactionId join Services c on c.Id=b.ServiceID where a.BillGenerated=0 and a.Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetPatientTransctionForBill() As String
            Get
                Return ResourceManager.GetString("GetPatientTransctionForBill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM PatientTransactions WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetTransactionDetailsById() As String
            Get
                Return ResourceManager.GetString("GetTransactionDetailsById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO ServiceTransactions(ServiceID, Amount, PatientTransactionId, CreateDate, CreateBy,ReportStatusId) VALUES(@ServiceID, @Amount, @PatientTransactionId, @CreateDate,@CreateBy,@ReportStatusId); SELECT SCOPE_IDENTITY();.
        '''</summary>
        Friend Shared ReadOnly Property SavePatientServices() As String
            Get
                Return ResourceManager.GetString("SavePatientServices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO PatientBillTransactions(PatientBillId,PatientTransactionId,ServiceTransactionId,CreateDate,CreateBy) VALUES(@PatientBillId,@PatientTransactionId,@ServiceTransactionId,@CreateDate,@CreateBy).
        '''</summary>
        Friend Shared ReadOnly Property SavePatientTBillTransctions() As String
            Get
                Return ResourceManager.GetString("SavePatientTBillTransctions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO PatientTransactions(DepositAmount, SampleRequired, SampleReceived, SampleNumber,BillGenerated,RefDocId, PatientId,CreateDate, CreateBy,Remarks,ReportStatusId) VALUES(@DepositAmount,@SampleRequired, @SampleReceived, @SampleNumber,@BillGenerated, @RefDocId, @PatientId, @CreateDate, @CreateBy,@Remarks,@ReportStatusId) ; SELECT SCOPE_IDENTITY();.
        '''</summary>
        Friend Shared ReadOnly Property SavePatientTransction() As String
            Get
                Return ResourceManager.GetString("SavePatientTransction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to insert into PatientBills(BillNo,PatientId,PatientTransactionId,TotalAmount,DiscountPercentage,DiscountAmount,Status,IsCancel,PaymentMode,PaymentDateTime,CreateDate,CreateBy,Remarks) values (@BillNo,@PatientId,@PatientTransactionId,@TotalAmount,@DiscountPercentage,@DiscountAmount,@Status,@IsCancel,@PaymentMode,@PaymentDateTime,@CreateDate,@CreateBy,@Remarks); SELECT SCOPE_IDENTITY();.
        '''</summary>
        Friend Shared ReadOnly Property SavePatientTransctionBill() As String
            Get
                Return ResourceManager.GetString("SavePatientTransctionBill", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update Settings set Value=@Value where Name=&apos;BillPrefix&apos;.
        '''</summary>
        Friend Shared ReadOnly Property UpdateBillNoForTransction() As String
            Get
                Return ResourceManager.GetString("UpdateBillNoForTransction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE ServiceTransactions SET ServiceID=@ServiceID, Amount=@Amount, PatientTransactionId=@PatientTransactionId, UpdateDate=@UpdateDate, UpdateBy=@UpdateBy , ReportStatusId = @ReportStatusId WHERE Id=@Id; SELECT SCOPE_IDENTITY();.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePatientServices() As String
            Get
                Return ResourceManager.GetString("UpdatePatientServices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE ServiceTransactions SET ServiceID=@ServiceID, Amount=@Amount, PatientTransactionId=@PatientTransactionId,  UpdateDate=@UpdateDate, UpdateBy=@UpdateBy ; SELECT SCOPE_IDENTITY();.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePatientServicess() As String
            Get
                Return ResourceManager.GetString("UpdatePatientServicess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE PatientTransactions SET DepositAmount=@DepositAmount, SampleRequired=@SampleRequired , SampleReceived=@SampleReceived, SampleNumber=@SampleNumber, BillGenerated=@BillGenerated, RefDocId=@RefDocId,PatientId=@PatientId, UpdateDate=@UpdateDate, UpdateBy=@UpdateBy , Remarks=@Remarks WHERE Id=@Id; SELECT SCOPE_IDENTITY();.
        '''</summary>
        Friend Shared ReadOnly Property UpdatePatientTransaction() As String
            Get
                Return ResourceManager.GetString("UpdatePatientTransaction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE ServiceTransactions
        '''SET ReportStatusId = @ReportStatusId,UpdateDate = @UpdateDate
        '''WHERE Id = @Id;.
        '''</summary>
        Friend Shared ReadOnly Property UpdateServiceTransaction() As String
            Get
                Return ResourceManager.GetString("UpdateServiceTransaction", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
