'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ServiceMaster
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProLab.Data.ServiceMaster", GetType(ServiceMaster).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select Name from Services where Name=@Name.
        '''</summary>
        Friend Shared ReadOnly Property CheckService() As String
            Get
                Return ResourceManager.GetString("CheckService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select CategoryName from ServiceCategory where CategoryName=@CategoryName.
        '''</summary>
        Friend Shared ReadOnly Property CheckServiceCategory() As String
            Get
                Return ResourceManager.GetString("CheckServiceCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM Doctors WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property DeleteDoctors() As String
            Get
                Return ResourceManager.GetString("DeleteDoctors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM Hospitals WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property DeleteHospital() As String
            Get
                Return ResourceManager.GetString("DeleteHospital", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM Services WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property DeleteService() As String
            Get
                Return ResourceManager.GetString("DeleteService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE FROM ServiceCategory WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property DeleteServiceCategoryById() As String
            Get
                Return ResourceManager.GetString("DeleteServiceCategoryById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM ServiceCategory ORDER BY CategoryName.
        '''</summary>
        Friend Shared ReadOnly Property GetAllServiceCategory() As String
            Get
                Return ResourceManager.GetString("GetAllServiceCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Services.
        '''</summary>
        Friend Shared ReadOnly Property GetAllServices() As String
            Get
                Return ResourceManager.GetString("GetAllServices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Doctors WHERE FirstName=@FirstName.
        '''</summary>
        Friend Shared ReadOnly Property GetDoctorByFirstName() As String
            Get
                Return ResourceManager.GetString("GetDoctorByFirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT a.*,b.Name as HospitalName FROM Doctors a,Hospitals b WHERE FirstName=@FirstName and LastName=@LastName.
        '''</summary>
        Friend Shared ReadOnly Property GetDoctorByFullName() As String
            Get
                Return ResourceManager.GetString("GetDoctorByFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select a.*,b.Name + &apos; ( &apos; + c.CityName + &apos; ) &apos; as HospitalName from Doctors a,Hospitals b,City c where a.HospitalId=b.Id and a.Id=@Id and b.CityId=c.Id.
        '''</summary>
        Friend Shared ReadOnly Property GetDoctorDetailsForTransction() As String
            Get
                Return ResourceManager.GetString("GetDoctorDetailsForTransction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Doctors WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetDoctrosById() As String
            Get
                Return ResourceManager.GetString("GetDoctrosById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Hospitals WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetHospitalById() As String
            Get
                Return ResourceManager.GetString("GetHospitalById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Hospitals WHERE Name=@Name.
        '''</summary>
        Friend Shared ReadOnly Property GetHospitalByName() As String
            Get
                Return ResourceManager.GetString("GetHospitalByName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Hospitals  ORDER BY Name.
        '''</summary>
        Friend Shared ReadOnly Property GetHospitalForDoctor() As String
            Get
                Return ResourceManager.GetString("GetHospitalForDoctor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT a.Id,a.Name + &apos; (&apos; +b.CityName +&apos;) &apos; as Name  FROM Hospitals a,City b WHERE a.CityId=b.Id ORDER BY a.Name, b.CityName.
        '''</summary>
        Friend Shared ReadOnly Property GetHospitalWithCity() As String
            Get
                Return ResourceManager.GetString("GetHospitalWithCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Services WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetServiceById() As String
            Get
                Return ResourceManager.GetString("GetServiceById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM Services WHERE Name=@Name.
        '''</summary>
        Friend Shared ReadOnly Property GetServiceByName() As String
            Get
                Return ResourceManager.GetString("GetServiceByName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM ServiceCategory Order By CategoryName.
        '''</summary>
        Friend Shared ReadOnly Property GetServiceCategory() As String
            Get
                Return ResourceManager.GetString("GetServiceCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM ServiceCategory WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property GetServiceCategoryById() As String
            Get
                Return ResourceManager.GetString("GetServiceCategoryById", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT * FROM ServiceCategory WHERE CategoryName=@CategoryName.
        '''</summary>
        Friend Shared ReadOnly Property GetServiceCategoryByName() As String
            Get
                Return ResourceManager.GetString("GetServiceCategoryByName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select  a.*,b.CategoryName from Services a,ServiceCategory b  where a.Id=@Id and a.Name=@Name and a.CategoryId=b.Id.
        '''</summary>
        Friend Shared ReadOnly Property GetServiceDetailsForTransction() As String
            Get
                Return ResourceManager.GetString("GetServiceDetailsForTransction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO Doctors(FirstName,LastName,HospitalId,CreateDate,CreateBy) VALUES(@FirstName,@LastName,@HospitalId,@CreateDate,@CreateBy).
        '''</summary>
        Friend Shared ReadOnly Property SaveDoctors() As String
            Get
                Return ResourceManager.GetString("SaveDoctors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO Hospitals(Name,Address1,Address2,Phone1,Phone2,CityId,CountryId,StateId,CreateDate,CreateBy) VALUES(@Name,@Address1,@Address2,@Phone1,@Phone2,@CityId,@CountryId,@StateId,@CreateDate,@CreateBy).
        '''</summary>
        Friend Shared ReadOnly Property SaveHospital() As String
            Get
                Return ResourceManager.GetString("SaveHospital", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO Services(CategoryId,Name,Amount,Description,AppoinmentNeeded,IsActive,CreateDate,CreateBy) VALUES(@CategoryId,@Name,@Amount,@Description,@AppoinmentNeeded,@IsActive,@CreateDate,@CreateBy).
        '''</summary>
        Friend Shared ReadOnly Property SaveService() As String
            Get
                Return ResourceManager.GetString("SaveService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO ServiceCategory(CategoryName,Description,CreateDate,CreateBy) VALUES(@CategoryName,@Description,@CreateDate,@CreateBy).
        '''</summary>
        Friend Shared ReadOnly Property SaveServiceCategory() As String
            Get
                Return ResourceManager.GetString("SaveServiceCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Doctors SET FirstName=@FirstName, LastName = @LastName, HospitalId=@HospitalId , UpdateDate = @UpdateDate, UpdateBy = @UpdateBy WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property UpdateDoctors() As String
            Get
                Return ResourceManager.GetString("UpdateDoctors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Hospitals SET Name=@Name,Address1=@Address1,Address2=@Address2 ,Phone1=@Phone1, Phone2 = @Phone2, CityId=@CityId ,CountryId=@CountryId, StateId=@StateId , UpdateDate = @UpdateDate, UpdateBy = @UpdateBy WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property UpdateHospital() As String
            Get
                Return ResourceManager.GetString("UpdateHospital", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE Services SET CategoryId=@CategoryId,Name=@Name,Description=@Description,AppoinmentNeeded=@AppoinmentNeeded,IsActive=@IsActive , UpdateDate = @UpdateDate, UpdateBy = @UpdateBy WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property UpdateService() As String
            Get
                Return ResourceManager.GetString("UpdateService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE ServiceCategory SET CategoryName=@CategoryName, Description=@Description, UpdateDate = @UpdateDate, UpdateBy = @UpdateBy WHERE Id=@Id.
        '''</summary>
        Friend Shared ReadOnly Property UpdateServiceCategory() As String
            Get
                Return ResourceManager.GetString("UpdateServiceCategory", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
